### ISSUE TITLE
Exception: Unknown namespace prefix : xsd

### ISSUE THREAD

**Issue by bawee** [cidgoh/LexMapr#100]
Dear LexMapr Team, 

I am encountering an error when running lexmapr 0.7.2:

```
(lexmapr) bwee@fleming:/home/bwee/projects/lexmapr/test$ /home/bwee/projects/lexmapr/LexMapr/bin/lexmapr input2.csv -c config.json
Traceback (most recent call last):
  File "/home/bwee/projects/lexmapr/LexMapr/bin/lexmapr", line 57, in <module>
    lexmapr.pipeline.run(args)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/lexmapr/pipeline.py", line 47, in run
    ontology_lookup_table = pipeline_resources.get_config_resources(args.config, args.no_cache)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/lexmapr/pipeline_resources.py", line 124, in get_config_resources
    ontofetch = Ontology()
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/lexmapr/ontofetch.py", line 114, in __init__
    """, initNs = self.onto_helper.namespace),
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/processor.py", line 27, in prepareQuery
    ret = translateQuery(parseQuery(queryString), base, initNs)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 935, in translateQuery
    q[1], visitPost=functools.partial(translatePName, prologue=prologue)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 469, in traverse
    r = _traverse(tree, visitPre, visitPost)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 426, in _traverse
    e[k] = _traverse(val, visitPre, visitPost)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 426, in _traverse
    e[k] = _traverse(val, visitPre, visitPost)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 419, in _traverse
    return [_traverse(x, visitPre, visitPost) for x in e]
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 419, in <listcomp>
    return [_traverse(x, visitPre, visitPost) for x in e]
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 426, in _traverse
    e[k] = _traverse(val, visitPre, visitPost)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 426, in _traverse
    e[k] = _traverse(val, visitPre, visitPost)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 419, in _traverse
    return [_traverse(x, visitPre, visitPost) for x in e]
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 419, in <listcomp>
    return [_traverse(x, visitPre, visitPost) for x in e]
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 426, in _traverse
    e[k] = _traverse(val, visitPre, visitPost)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 426, in _traverse
    e[k] = _traverse(val, visitPre, visitPost)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 426, in _traverse
    e[k] = _traverse(val, visitPre, visitPost)
  [Previous line repeated 4 more times]
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 429, in _traverse
    _e = visitPost(e)  # type: ignore[unreachable]
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/algebra.py", line 197, in translatePName
    return prologue.absolutize(p)  # type: ignore[return-value]
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/sparql.py", line 430, in absolutize
    return self.resolvePName(iri.prefix, iri.localname)
  File "/home/bwee/miniconda3/envs/lexmapr/lib/python3.7/site-packages/rdflib/plugins/sparql/sparql.py", line 412, in resolvePName
    raise Exception("Unknown namespace prefix : %s" % prefix)
Exception: Unknown namespace prefix : xsd
```

Where input2.csv is:

```
SampleId,Sample
small_simple1,Chicken Breast
small_simple2,Baked Potato
small_simple3,Canned Corn
small_simple4,Frozen Yogurt
small_simple5,Apple Pie
```

And config.json (following your README example) is:

```
[
          {"http://purl.obolibrary.org/obo/foodon.owl": "http://purl.obolibrary.org/obo/BFO_0000001"}
]
```

It also throws the same error when using other ontologies, e.g. envo. But runs fine when no -c is given. 

Any guidance would be much appreciated!

Bryan

**Comment by ivansg44** [comment]
Hi, the xsd prefix is referenced in a sparql query. We did not properly define it in recent updates. Will publish a new release shortly.

**Comment by ivansg44** [comment]
v0.7.3 is out now

**Comment by bawee** [comment]
Thanks @ivansg44 , the updated code works as expected now. However, just to let you know, the code's version number has not been incremented in the init file.
